### ISSUE TITLE
0.2 CIA release

### ISSUE THREAD

**Issue by hacker1024** [mholtkamp/retro-league#1]
Hi,
This is an amazing bit of homebrew (I'm really impressed!) and I can't wait to tinker with it when you release the source code.
Until then, would you mind uploading a CIA release of 0.2 as we can't build it ourselves?

**Comment by mholtkamp** [comment]
Hello! Thanks for reaching out, sorry it took a while to get back to you. I just uploaded a CIA for the 0.2 version on the release page. Well... it's actually not v0.2, there are a few extra features like shadows on the ball and the cars. But it should be compatible with the other versions. If you still need the true v0.2, or if something isn't working correctly, I can build it for you. It will just take me some extra time since.
